version: "3"
services:
  nginx:
    container_name: dap-nginx-server
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
  api:
    container_name: dap-server
    build:
      dockerfile: Dockerfile
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
  client:
    container_name: dap-client
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./client
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BASE_URL= ""
    volumes:
      - /app/node_modules
      - ./client:/app
